CREATE TABLE shows (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      UUID         NOT NULL,
    name           VARCHAR(128) NOT NULL,
    price_paise    BIGINT       NOT NULL,
    per_user_limit SMALLINT     NOT NULL,
    total_seats    INTEGER      NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_shows_public_id  UNIQUE (public_id),
    CONSTRAINT uq_shows_name       UNIQUE (name),
    CONSTRAINT ck_shows_price      CHECK (price_paise >= 0),
    CONSTRAINT ck_shows_limit      CHECK (per_user_limit > 0),
    CONSTRAINT ck_shows_seats      CHECK (total_seats > 0)
);

CREATE TABLE reservations (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    UUID        NOT NULL,
    show_id      BIGINT      NOT NULL REFERENCES shows (id),
    user_id      VARCHAR(64) NOT NULL,
    status       VARCHAR(16) NOT NULL,
    amount_paise BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ,
    CONSTRAINT uq_reservations_public_id UNIQUE (public_id),
    CONSTRAINT ck_reservations_amount    CHECK (amount_paise >= 0),
    CONSTRAINT ck_reservations_status    CHECK (status IN ('HELD', 'CONFIRMED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT ck_reservations_expiry    CHECK (status <> 'HELD' OR expires_at IS NOT NULL)
);

CREATE INDEX ix_reservations_owner ON reservations (show_id, user_id);

CREATE TABLE seats (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id         BIGINT      NOT NULL REFERENCES shows (id),
    label           VARCHAR(16) NOT NULL,
    status          VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    claimed_by      VARCHAR(64),
    hold_expires_at TIMESTAMPTZ,
    reservation_id  BIGINT REFERENCES reservations (id),
    CONSTRAINT uq_seats_show_label UNIQUE (show_id, label),
    CONSTRAINT ck_seats_status     CHECK (status IN ('AVAILABLE', 'HELD', 'CONFIRMED')),
    CONSTRAINT ck_seats_available  CHECK (status <> 'AVAILABLE'
                                          OR (claimed_by IS NULL AND hold_expires_at IS NULL AND reservation_id IS NULL)),
    CONSTRAINT ck_seats_held       CHECK (status <> 'HELD'
                                          OR (claimed_by IS NOT NULL AND hold_expires_at IS NOT NULL AND reservation_id IS NOT NULL)),
    CONSTRAINT ck_seats_confirmed  CHECK (status <> 'CONFIRMED'
                                          OR (claimed_by IS NOT NULL AND hold_expires_at IS NULL AND reservation_id IS NOT NULL))
);

CREATE INDEX ix_seats_owner     ON seats (show_id, claimed_by) WHERE claimed_by IS NOT NULL;
CREATE INDEX ix_seats_expiring  ON seats (hold_expires_at)     WHERE status = 'HELD';

CREATE TABLE idempotency_keys (
    user_id             VARCHAR(64)  NOT NULL,
    idempotency_key     VARCHAR(128) NOT NULL,
    request_fingerprint VARCHAR(64)  NOT NULL,
    reservation_id      BIGINT REFERENCES reservations (id),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, idempotency_key)
);
