CREATE TABLE users (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID        NOT NULL,
    username      VARCHAR(64) NOT NULL,
    password_hash VARCHAR(72) NOT NULL,
    role          VARCHAR(16) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_public_id UNIQUE (public_id),
    CONSTRAINT uq_users_username  UNIQUE (username),
    CONSTRAINT ck_users_role      CHECK (role IN ('USER', 'ADMIN'))
);
